feat: Make url for event shorter
bc-compsci-club/bccs-club pull request #114
Opened 2024-12-15 04:22 UTC by birongliu

- added getEvent, getEvents server actions to help with fetching event data on server instead on client side
- resolve #89 

Uploading Screen Recording 2024-12-14 at 11.12.38 PM.mov…

2024-12-26 22:16 UTC, jellyfishing2346 requested changes
Hi @birongliu, 

It appears that the some of the days for the club hours is incorrect. 
Please note: Tuesday's club hours are 1:00-3:30pm and Wednesday's club hours are 12-2pm. 
<img width="1470" alt="Screenshot 2024-12-26 at 5 12 13 PM" src="https://github.com/user-attachments/assets/194d9a61-2990-4132-9234-afdaccd816cd" />
<img width="1468" alt="Screenshot 2024-12-26 at 5 13 18 PM" src="https://github.com/user-attachments/assets/5b3a44f2-f596-4059-a65b-77f444529bf3" />
Also the timing for the virtual career panel is incorrect. 
Also please fill the remaining club hours for the remaining time in November and December before finals week.

2024-12-31 22:08 UTC, qingquan-li commented on .vscode/settings.json
It would be better to add `.vscode/` to `.gitignore` if you don't want to track it anymore.

2025-01-02 19:31 UTC, qingquan-li reviewed
Looks awesome. great job! just some small issues to address before merging!

2025-01-02 19:31 UTC, qingquan-li commented on frontend/app/utils/types.ts
please add `slug: string;`

2025-01-02 19:31 UTC, qingquan-li commented on frontend/app/(portal)/events/page.tsx
> +    router.push(`/events/${title}-${date}`);
Is it better to use
```
router.push(`/events/${a.slug}`);
```
to keep the consistance?

If you generate the slug (date part) in the frontend, it may generate a different slug because in the backend (api), I added timezone to it:
```
// Method to generate slug: title + date
private void generateSlug() {
    if (this.title == null || this.startTime == null) {
        throw new IllegalStateException("title or startTime is null. Cannot generate slug.");
    }
    // Convert title to lowercase, replace non-alphanumeric characters with hyphens
    String baseSlug = this.title.toLowerCase().replaceAll("[^a-z0-9]+", "-").replaceAll("(^-|-$)", "");
    // Convert startTime to ZonedDateTime in America/New_York timezone
    ZonedDateTime zonedDateTime = this.startTime.atZone(java.time.ZoneId.of("America/New_York"));
    String datePart = zonedDateTime.toLocalDate().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"));
    this.slug = baseSlug + "-" + datePart;
}
```

2025-01-02 19:42 UTC, birongliu commented on frontend/app/(portal)/events/page.tsx
> +    router.push(`/events/${title}-${date}`);
resolved

2025-01-02 20:52 UTC, qingquan-li approved these changes

2025-01-02 20:52 UTC, merged